#:schema node_modules/wrangler/config-schema.json
name = "lovely-site"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "lovely-site-db"
database_id = "ed2f83e9-07b8-4d2f-b0e7-788c4cfee4a0"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "lovelymain"
